### PR TITLE
Derive default from variant types

### LINKED ISSUE #6: Derive default from variant types
We need to be able to derive default values from variant types.
We should at least handle non parametrized variant types.

In the case of parametrized variant types we'd ideally like to be able to detect whether a generic default can be derived and do so or fail otherwise.

Ie in this example code
```ocaml
type ('a, 'b) t =
  | A of 'a
  | B of 'b
[@@deriving default]

type ('a, 'b) u =
  | A of 'a
  | B of 'b
  | C
[@@deriving default]
```
We should be able to derive the following default for `u`
```ocaml
let default = C
```
but fail on `t`

### PR DESCRIPTION
**Pull request by NathanReb**
Fixes #6.

### CODE REVIEW

**Comment by NathanReb** [comment]
Marked as WIP since it's based on #8!

**Comment by NathanReb** [comment]
Rebased and unWIPed!

File: lib/default.ml [hunk 1]
```diff
@@ -13,23 +13,29 @@ let expr_from_lident ~loc {txt; loc = err_loc} =
...
-  | Ptyp_var _ -> Raise.errorf ~loc:ptyp_loc "can't derive default for unspecified type" 
-  | _ -> Raise.errorf ~loc:ptyp_loc "can't derive default value from this type"
+    ( match Util.List_.all_ok expr_list with
+      | Ok expr_list -> Ok (Ast_builder.Default.pexp_tuple ~loc expr_list)
+      | Error _ as err -> err
+    )
+  | Ptyp_var _ -> Loc_err.as_result ~loc:ptyp_loc ~msg:"can't derive default for unspecified type" 
+  | _ -> Loc_err.as_result ~loc:ptyp_loc ~msg:"can't derive default from this type"
+
+let expr_from_core_type_exn ~loc core_type =
```
Comment (leamingrad) [inline lib/default.ml:37]: I think this could possibly be named a bit more descriptively - maybe something like `expr_from_core_type_maybe_raise_exn` or something?

File: lib/default.ml [hunk 2]
```diff
@@ -38,27 +44,73 @@ module Str = struct
...
+    expr_from_core_type ~loc pld_type >|= fun expr ->
     (lident, expr)
 
   let value_expr_from_labels ~loc labels =
+    let open Util.Result_ in
     let field_bindings = List.map (field_binding ~loc) labels in
+    Util.List_.all_ok field_bindings >|= fun field_bindings ->
     Ast_builder.Default.pexp_record ~loc field_bindings None
 
+  let value_expr_from_labels_exn ~loc labels =
```
Comment (leamingrad) [inline lib/default.ml:61]: Why has this change led to all these new functions - they don't seem to be for variant types?

File: lib/default.ml [hunk 3]
```diff
@@ -38,27 +44,73 @@ module Str = struct
...
+    let open Util.Result_ in
+    let expr_list = List.map (expr_from_core_type ~loc) types in
+    match expr_list with
+    | [] -> Ok None
+    | [expr] -> expr >|= fun expr -> Some expr
+    | _ ->
+      Util.List_.all_ok expr_list >|= fun expr_list ->
+      Some (Ast_builder.Default.pexp_tuple ~loc expr_list)
+
+  let value_expr_from_ctor ~loc {pcd_name = {txt = ctr_name; _}; pcd_args; _} =
```
Comment (leamingrad) [inline lib/default.ml]: What do `ctr` and `ctor` mean (and could they be named a bit more descriptively)?

**Review by leamingrad — COMMENTED** [review]
Generally looks good to me - most of my comments are "I can't work out what this does from the name, can it be a bit more verbose"

File: lib/default.ml (hunk 1 above)
Comment (NathanReb) [reply lib/default.ml:37]: I think the `_exn` suffix is pretty standard and the function is documented so I'm not sure this would bring much value.

File: lib/default.ml (hunk 3 above)
Comment (NathanReb) [reply lib/default.ml]: They stand for `constructor`, I'll replace them!

File: lib/default.ml (hunk 2 above)
Comment (NathanReb) [reply lib/default.ml:61]: The `value_expr_from_labels` is shared between the functions that return a default expression for a record and for a variant who's argument is a record.

When deriving a default value for a variant type we need to go through each constructor see if we can derive a generic default value for its arguments. Using a result makes this easier and more elegant. In the record case, if we can't derive a default for the record it's game over straigt away so we're using a wrapper that raise the error that will be displayed to the end user.

Does it make more sense now?

File: lib/default.ml (hunk 1 above)
Comment (leamingrad) [reply lib/default.ml:37]: Yeah thats fine

**Comment by NathanReb** [comment]
Just pushed another commit to rename `ctr` and `ctor` by `constructor`. Let me know if it improved clarity!

File: lib/default.ml (hunk 2 above)
Comment (leamingrad) [reply lib/default.ml:61]: Yep

**Review by leamingrad — APPROVED** [review]
