### PR TITLE
Make ppx_factory compatible with ppx_import

### LINKED ISSUE #12: Compatibility with ppx_import
Atm `[@@deriving factory]` doesn't work with `ppx_import`.

Ppx-es are called twice, first with `ocamldep` to resolve dependencies of a module, including dependencies of the generated code, and then with the actual compiler.

Because `ppx_import` needs bits of information from `.cmi` files, when called with `ocamldep` it can't expand completely and thus only expands into an abstract type. For example the following code:
```ocaml
type t = [%import: A.t]
```
is expanded as:
```ocaml
type t = A.t
```
during the first phase and as:
```ocaml
type t = A.t = ...
```
during the second.

Because we don't derive factories for abstract types, using both `ppx_import` and `ppx_factory` will make the build fail during that first phase.

In order for it to work, we'd ideally need to have a special case when called from `ocamldep` so that abstract types are silently "skipped" and only trigger an error during that second phase.

See https://github.com/ocaml/dune/issues/1861 for details.

### PR DESCRIPTION
**Pull request by NathanReb**
Fixes #12.

This is done by not failing on abstract types. Because ppxlib doesn't expose the tool_name, we can't do it selectively in an ocamldep context and have to always silently do nothing for such types.

This should be fixed as soon as possible.

### CODE REVIEW

File: lib/factory.ml [hunk 1]
```diff
@@ -95,7 +95,7 @@ module Str = struct
     match ptype_kind with
     | Ptype_record labels -> from_record ~loc ~type_name ~labels
     | Ptype_variant constructors -> List.map (from_constructor ~loc ~type_name) constructors
-    | Ptype_abstract -> Raise.Factory.unhandled_type_kind ~loc "abstract"
+    | Ptype_abstract -> []
```
Comment (leamingrad) [inline lib/factory.ml:98]: Is it worth logging a warning or something (not sure if this is allowed inside a ppx) so that the user knows they used an abstract type, knows we ignored it and has a link to an issue they can follow for resolution?

File: lib/factory.ml [hunk 2]
```diff
@@ -160,7 +160,7 @@ module Sig = struct
     match ptype_kind with
     | Ptype_record labels -> from_record ~loc ~type_name ~return_type ~labels
     | Ptype_variant ctors -> List.map (from_constructor ~loc ~type_name ~return_type) ctors
-    | Ptype_abstract -> Raise.Factory.unhandled_type_kind ~loc "abstract"
+    | Ptype_abstract -> []
```
Comment (leamingrad) [inline lib/factory.ml:163]: Its weird that this doesn't break any tests? Should we add a test for this behaviour?

**Review by leamingrad — CHANGES_REQUESTED** [review]

File: lib/factory.ml (hunk 1 above)
Comment (NathanReb) [reply lib/factory.ml:98]: I'll have a look but I'm not sure there's a well supported way to do that.

File: lib/factory.ml (hunk 2 above)
Comment (NathanReb) [reply lib/factory.ml:163]: That's because we don't test errors atm. I'd like to be able to test errors and their locations but I need to figure out an easy way to do that first!
